#!/usr/bin/env python3
# =====================================================================
#  embed_web.py — PlatformIO pre-build script.
#  Gzips every file under data/ and generates src/web_assets.h so the
#  web UI is served from firmware (PROGMEM). This removes the need for
#  `uploadfs`, so the LittleFS partition (history + logs) is never
#  rewritten by deploys and survives all OTA updates.
# =====================================================================
import os, gzip, io

Import("env")  # noqa: F821  (provided by PlatformIO/SCons)

PROJECT_DIR = env["PROJECT_DIR"]            # noqa: F821
DATA_DIR = os.path.join(PROJECT_DIR, "data")
OUT = os.path.join(PROJECT_DIR, "src", "web_assets.h")

MIME = {
    ".html": "text/html", ".css": "text/css", ".js": "application/javascript",
    ".json": "application/json", ".svg": "image/svg+xml", ".ico": "image/x-icon",
    ".png": "image/png", ".woff2": "font/woff2",
}

def mime_for(path):
    return MIME.get(os.path.splitext(path)[1].lower(), "text/plain")

def gather(root):
    items = []
    for base, _dirs, files in os.walk(root):
        for fn in files:
            full = os.path.join(base, fn)
            rel = "/" + os.path.relpath(full, root).replace(os.sep, "/")
            items.append((rel, full))
    return sorted(items)

def gz(data):
    buf = io.BytesIO()
    with gzip.GzipFile(fileobj=buf, mode="wb", compresslevel=9, mtime=0) as f:
        f.write(data)
    return buf.getvalue()

def main():
    items = gather(DATA_DIR)
    total = 0
    lines = [
        "// AUTO-GENERATED by scripts/embed_web.py — do not edit.",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        "struct WebAsset { const char* path; const char* mime; "
        "const uint8_t* data; unsigned len; };",
        "",
    ]
    table = []
    for i, (rel, full) in enumerate(items):
        with open(full, "rb") as fh:
            comp = gz(fh.read())
        total += len(comp)
        arr = ",".join(str(b) for b in comp)
        lines.append(f"static const uint8_t asset_{i}[] PROGMEM = {{{arr}}};")
        table.append(f'  {{ "{rel}", "{mime_for(rel)}", asset_{i}, {len(comp)} }},')
    lines.append("")
    lines.append("static const WebAsset WEB_ASSETS[] = {")
    lines.extend(table)
    lines.append("};")
    lines.append(f"static const int WEB_ASSET_COUNT = {len(items)};")
    lines.append("")
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"[embed_web] embedded {len(items)} files, {total} bytes gzipped "
          f"-> {os.path.relpath(OUT, PROJECT_DIR)}")

main()
